### ISSUE TITLE
Black screen caused by custom cursor

### ISSUE THREAD

**Issue by benjaminbra** [ESX-Org/esx_atm#16]
When using ATM, if you select the amount by using the cursor, the screen goes black.

The only way to leave is to close the game.

I don't know why, but the custom cursor is a trouble maker when using long click.

The best way to fix this, is to remove cursor and activate native cursor by doing 'SetNuiFocus(true, true)' when you open the UI.

**Comment by ElPumpo** [comment]
Really annoying I know, thanks for the tip i'll try it out.

**Comment by benjaminbra** [comment]
Now that the fix is merged, we can close this issue.

**Comment by ElPumpo** [comment]
You're right
