### ISSUE TITLE
Can't See ATM in the map

### ISSUE THREAD

**Issue by FuTuRNeT** [ESX-Org/esx_atm#20]
Hi, 
i have a problem with the ATM script.
the file is bein loaded working fine in console, but i can't see the ATM in the MAP

Best Regards
Akram

**Comment by benjaminbra** [comment]
If i remember well, atm blip got removed by default.
In config.lua, set `Config.EnableBlips = false` to `Config.EnableBlips = true`

**Comment by FuTuRNeT** [comment]
Good morning, 

Yes :) i forget this. 
but this post could help another person :)

Thank you :) 

Best regards
Akram

**Comment by ElPumpo** [comment]
Are you stuiped?
